version: "3.8"

services:
  backend:
    image: balupatil999/clouddrop-backend
    container_name: clouddrop_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.docker
    depends_on:
      - mongo

  frontend:
    image: balupatil999/clouddrop-frontend
    container_name: clouddrop_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: clouddrop_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: